version: "3.7"
services:
  blinky-mqtt-trays:
    image: blinkylite/blinky-mqtt-trays:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-mqtt-trays-${TRAYTYPE}
#    ports:
#      - "${NODEREDPORT}:60428"
    environment:
      - BOX=${BOX}
      - TRAYTYPE=${TRAYTYPE}
      - MQTTCLIENTID=${BOX}-${TRAYTYPE}
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYPASSWORD}
      - MQTTPORT=1883
      - NODEREDPORT=60428
      - ENABLE_NODERED_EDITOR=${ENABLE_NODERED_EDITOR}
networks:
  default:
    name: tunnel
    external: true


